### ISSUE TITLE
Request: Real time lower toolbar counter

### ISSUE THREAD

**Issue by csfalcao** [cfjedimaster/Word-Count-Extension#1]
Add the word counter in the lower bar beside the line and column counter, with real time update.

**Comment by csfalcao** [comment]
A GUI draft:
1) Lower bar word counter (left bottom) inside separator
2) Without separator
![word-counter_new_separator](https://cloud.githubusercontent.com/assets/2768615/8803095/4d0a1c76-2f9b-11e5-81e3-721a36b3c612.jpg)
![word-counter_new](https://cloud.githubusercontent.com/assets/2768615/8803096/4d363a68-2f9b-11e5-90a8-176648a9ea30.jpg)

**Comment by cfjedimaster** [comment]
I see you appear to have an extension modifying the bottom already - eqFTPQueue. What extension is that?

**Comment by csfalcao** [comment]
Well observed! It's a plugging for acessing FTP/sFTP. It's here: https://github.com/Equals182/eqFTP. Now it's easier to style :+1:

**Comment by cfjedimaster** [comment]
This was a damn good idea. I've updated the ext to no longer use a menu. It
just uses the bottom panel. Much, much better.

On Tue, Jul 21, 2015 at 9:30 PM, Cesar S Falcão notifications@github.com
wrote:

> Well observed! It's a plugging for acessing FTP/sFTP. It's here:
> https://github.com/Equals182/eqFTP.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/cfjedimaster/Word-Count-Extension/issues/1#issuecomment-123537766
> .

## 

# 

Raymond Camden, Developer Advocate for MobileFirst at IBM

Email : raymondcamden@gmail.com
Blog : www.raymondcamden.com
Twitter: raymondcamden

**Comment by csfalcao** [comment]
Great work! (y) But just a small question: the counter updates on save, so it don't update as you type, like the line and column in the lower bar. It's so good now, but if it's doable, it will get perfect.

**Thanks for the update**, you mad all the magic and my work is cooler now with your contribution !

**Comment by cfjedimaster** [comment]
I agree it would be nice. I tried to hack this myself but failed. Maybe
some one can do a PR for it. :)

On Sun, Jul 26, 2015 at 6:41 PM, Cesar S Falcão notifications@github.com
wrote:

> Great work! (y) But just a small question: the counter updates on save, so
> it don't update as you type, like the line and column in the lower bar.
> It's so good now, but if it's doable, it will get perfect.
> Thanks for the update, you mad all the magic and my work is cooler now
> with your contribution !
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/cfjedimaster/Word-Count-Extension/issues/1#issuecomment-125048462
> .

## 

# 

Raymond Camden, Developer Advocate for MobileFirst at IBM

Email : raymondcamden@gmail.com
Blog : www.raymondcamden.com
Twitter: raymondcamden

**Comment by csfalcao** [comment]
Thanks cfjedimaster, you'll figure it out someday. Word count is a nice brackets extension!

**Comment by cfjedimaster** [comment]
it is now realtime

**Comment by csfalcao** [comment]
Wow, Perfect! I think now you should delete "stupid" from your extension description ;)
PS - how you figure it out so fast?

**Comment by cfjedimaster** [comment]
I got some help on the Brackets Slack.

On Tue, Jul 28, 2015 at 8:18 PM, Cesar S Falcão notifications@github.com
wrote:

> Wow, Perfect! I think now you should delete "stupid" from your extension
> description ;)
> PS - how you figure it out so fast?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/cfjedimaster/Word-Count-Extension/issues/1#issuecomment-125796308
> .

## 

# 

Raymond Camden, Developer Advocate for MobileFirst at IBM

Email : raymondcamden@gmail.com
Blog : www.raymondcamden.com
Twitter: raymondcamden
